### ISSUE TITLE
Create an RPM package in OBS

### ISSUE THREAD

**Issue by tomschr** [dmpop/sonnenhut#17]
We would like to have an RPM package which can be nicely installed under openSUSE. 

# What you need

* OBS account and home
* `osc`, package `osc`  from `devel:tools:scm`
* `py2pack`, package `python3-py2pack` from `devel:languages:python3`
* `spec-cleaner`, package `spec-cleaner`

 # How it works

In your Git working repo:

1. Create a new release branch (`git flow release start VERSION`)
1. Update the `Changelog.rst` file.
1. Do whatever else is needed for your release.
1. Raise the version number with `bumpversion`.
1. Create the new release with: `git flow release finish`
1. Create a tarball with `./setup.py sdist`. Find the archive under the `dist/` directory.

In your OBS working repo:

1. Setup OBS and `osc` accordingly.
1. Create a new package directory with: `osc mkpac sonnenhut`
1. Create a new spec file in this directory.
1. Copy the archive from your `dist` directory to the OBS directory.
1. Check weather the version number in the filename and in the spec file are the same.
1. Create a `.changes` file with: `osc vc` and add a meaningful message.
1. Add all the files (`sonnenhut.changes`, `sonnenhut.spec`, and the tarball) to the repo with `osc add *`
1. Build the package locally with: `osc build -j4 openSUSE_Leap_42.2 x86_64 sonnenhut.spec`
1. Check, if the build was successful. If not, fix the errors.
1. Commit the package with: `osc ci`

Your done! Congratulations! 👍

**Comment by dmpop** [comment]
https://build.opensuse.org/package/show/home:dpopov/sonnenhut
