### ISSUE TITLE
Check for API changes

### ISSUE THREAD

**Issue by tomschr** [dmpop/sonnenhut#39]
To avoid any future problems with API changes from DarkSky, we should check for its version.

I haven't checked yet, but I guess they provide some version information in their Jon response.

At could check for this version and if it's not the version we expect we can give a nice error message.

**Comment by dmpop** [comment]
That's clever! Definitely worth implementing.

**Comment by tomschr** [comment]
Checking the DarkSky API at https://darksky.net/dev/docs didn't reveal me any versioning scheme. So this is sad news 😢 😞

There is an old API which were declared as deprecated (see http://status.darksky.net/2013/03/26/v2-api-released.html). It seems, the new v2 is now being used, but it doesn't introduce itself as such.

For the time being, I don't see any solution how to do it. Such clever ideas die on the wall of reality. 😆 

Feel free to close it or leave it as open.

**Comment by dmpop** [comment]
I see. Thanks for following up on this. I close it to keep things tidy.
